import './globals.css'
import { Inter } from 'next/font/google'
import { headers } from 'next/headers';
import 'server-only';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const lang = headers().get('x-language') || 'en';

  return (
    <html lang={lang}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
